global:
  scrape_interval: 15s
  evaluation_interval: 15s 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  #rule_1

scrape_configs:
  - job_name: "java-app"
    static_configs:
      - targets: ["192.168.1.12:8002"]

  - job_name: "python-app"
    static_configs:
      - targets: ["192.168.1.12:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]